"""ドメイン全体で使う列挙型。"""

from __future__ import annotations

from enum import StrEnum


class AccountType(StrEnum):
    SPECIFIC = "SPECIFIC"  # 特定口座
    NISA = "NISA"
    GENERAL = "GENERAL"  # 一般口座


class Priority(StrEnum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class ConfidenceLevel(StrEnum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class RecommendationType(StrEnum):
    """要求仕様26節。買い判定・保有判定・売却判定を一つの列挙で表現する。"""

    BUY = "BUY"
    WATCH_BUY = "WATCH_BUY"
    HOLD = "HOLD"
    WATCH = "WATCH"
    PARTIAL_PROFIT_TAKE = "PARTIAL_PROFIT_TAKE"
    FULL_PROFIT_TAKE = "FULL_PROFIT_TAKE"
    SELL = "SELL"
    URGENT_REVIEW = "URGENT_REVIEW"


class TransactionType(StrEnum):
    BUY = "BUY"
    ADDITIONAL_BUY = "ADDITIONAL_BUY"
    PARTIAL_SELL = "PARTIAL_SELL"
    FULL_SELL = "FULL_SELL"


class SkipReason(StrEnum):
    """要求仕様27節: 推奨に従わなかった場合の理由。"""

    PRICE_NOT_REACHED = "PRICE_NOT_REACHED"
    INSUFFICIENT_FUNDS = "INSUFFICIENT_FUNDS"
    PRIORITIZED_OTHER_STOCK = "PRIORITIZED_OTHER_STOCK"
    WAITED_FOR_EARNINGS = "WAITED_FOR_EARNINGS"
    NOT_CONVINCED = "NOT_CONVINCED"
    MANUAL_JUDGMENT = "MANUAL_JUDGMENT"
    OTHER = "OTHER"


class ApprovalStatus(StrEnum):
    DRAFT = "DRAFT"
    PROPOSED = "PROPOSED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    ACTIVE = "ACTIVE"
    ROLLED_BACK = "ROLLED_BACK"


class EvaluationLabel(StrEnum):
    SUCCESS = "SUCCESS"
    ACCEPTABLE = "ACCEPTABLE"
    EARLY = "EARLY"
    LATE = "LATE"
    PRICE_TOO_LOW = "PRICE_TOO_LOW"
    PRICE_TOO_HIGH = "PRICE_TOO_HIGH"
    PROFIT_TAKE_TOO_EARLY = "PROFIT_TAKE_TOO_EARLY"
    PROFIT_TAKE_TOO_LATE = "PROFIT_TAKE_TOO_LATE"
    SELL_TOO_SENSITIVE = "SELL_TOO_SENSITIVE"
    RISK_UNDERESTIMATED = "RISK_UNDERESTIMATED"
    DATA_ISSUE = "DATA_ISSUE"
    INCONCLUSIVE = "INCONCLUSIVE"


class NotificationType(StrEnum):
    DAILY_BUY_CANDIDATES = "DAILY_BUY_CANDIDATES"
    WATCHLIST_BUY_SIGNAL = "WATCHLIST_BUY_SIGNAL"
    PROFIT_TAKING_SIGNAL = "PROFIT_TAKING_SIGNAL"
    SELL_SIGNAL = "SELL_SIGNAL"
    IMPORTANT_DISCLOSURE = "IMPORTANT_DISCLOSURE"
    DATA_ERROR = "DATA_ERROR"
    WEEKLY_REVIEW = "WEEKLY_REVIEW"
    MONTHLY_REVIEW = "MONTHLY_REVIEW"
    QUARTERLY_LOGIC_REVIEW = "QUARTERLY_LOGIC_REVIEW"
    OUTLIER_REVIEW = "OUTLIER_REVIEW"
    LOGIC_CHANGE_PROPOSAL = "LOGIC_CHANGE_PROPOSAL"


class BenefitUtilityCategory(StrEnum):
    """要求仕様7節: 株主優待評価額の利用可能性係数カテゴリ。"""

    CASH_EQUIVALENT = "CASH_EQUIVALENT"
    VERSATILE_POINT = "VERSATILE_POINT"
    IN_HOUSE_SERVICE = "IN_HOUSE_SERVICE"
    IN_HOUSE_PRODUCT = "IN_HOUSE_PRODUCT"
    DISCOUNT_VOUCHER = "DISCOUNT_VOUCHER"
    LOTTERY_OR_COMMEMORATIVE = "LOTTERY_OR_COMMEMORATIVE"
